### ISSUE TITLE
Error with certificate on login

### ISSUE THREAD

**Issue by ordrlyhman** [JKetelaar/PHP-FUT-API#20]
I'm getting an error while I'm trying to login
Message: Unable to login with unknown response With the following message: Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: unable to get local issuer certificate
With error code: 60

**Comment by JKetelaar** [comment]
What operating system are you using?

**Comment by ordrlyhman** [comment]
I'm using windows with phpstorm

**Comment by JKetelaar** [comment]
I'll try to reproduce the error ASAP and get back to you!

**Comment by ordrlyhman** [comment]
Thanks for the help!

**Comment by JKetelaar** [comment]
With my test script I'm getting the following results (no errors):
```
/Applications/MAMP/bin/php/php5.6.27/bin/php -d display_errors "/Volumes/OTHER/FUT/FUT Bot/test.php"
We're logged in!

Found 0 players having a pace bigger than 85.
Process finished with exit code 0
```

Could you provide some information about your local environment, like what PHP version, using default PHP installed or with MAMP?
Might even provide results using `php -i` and paste it here.

**Comment by JKetelaar** [comment]
This also seems like an error where it would be your environment only, as it isn't accepting the SSL certificate.

I might implement a way to disable the SSL check, but I'll wait for your results first.

**Comment by JKetelaar** [comment]
Any update on this @ExecutableFix?

**Comment by JKetelaar** [comment]
Closed due no response.
