### ISSUE TITLE
X_UT_ROUTE changed

### ISSUE THREAD

**Issue by xfuturomax** [JKetelaar/PHP-FUT-API#21]
Now it is:
const X_UT_ROUTE             = 'https://utas.external.fut.ea.com'; (vendor/jketelaar/php-fut-api/src/JKetelaar/fut/bot/config/Configuration.php:19)

another way got: 500 Internal

**Comment by JKetelaar** [comment]
Do you, by any chance, know the new route endpoint?

**Comment by xfuturomax** [comment]
This is new route: 'https://utas.external.fut.ea.com'
Your old is not working :(

**Comment by JKetelaar** [comment]
Fixed with the latest PR, will be merged soon!

**Comment by JKetelaar** [comment]
Fixed in version 0.0.4

Can you test if it works now, my unit test seem to work 👍

**Comment by xfuturomax** [comment]
Now it works, thanks. 

And i think you can change readme: composer require jketelaar/php-fut-bot => composer require jketelaar/php-fut-api
