### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by Albvadi** [JKetelaar/PHP-FUT-API#26]
Hi, trying to use the API, I get the following error:

`
Fatal error: Uncaught JKetelaar\fut\api\errors\login\MainLogin: Unable to login with unknown response With the following message: Peer certificate cannot be authenticated with given CA certificates: SSL certificate problem: unable to get local issuer certificate With error code: 60 in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php:110
Stack trace: #0 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php(90): JKetelaar\fut\api\user\Login->requestMain() #1 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\API.php(114): JKetelaar\fut\api\user\Login->login() #2 C:\xampp_7\htdocs\fut17\index.php(8): JKetelaar\fut\api\API->login() #3 {main} thrown in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php on line 110
`

Adding `$curl->setOpt(CURLOPT_SSL_VERIFYPEER, false);` in `/vendor/jketelaar/php-fut-api/src/JKetelaar/fut/api/user/Login.php` in `setupCurl()` solves the problem, but, maybe it´s not the best way...

Thanks!

**Comment by JKetelaar** [comment]
I've seen this question before, does it relate to this issue #20?

**Comment by Albvadi** [comment]
Yep, same symptoms.

My environment setup:
- S.O: Windows 10 (x86)
- Web Server:  ApacheFriends XAMPP Version 7.0.13 
- PHP Version (included in XAMPP): `PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies`

Tell me if you need more info..
Thanks!

**Comment by JKetelaar** [comment]
Could you try this with the latest release (0.0.4.1)

As explained in the docs:
```
$api = new \JKetelaar\fut\api\API('your@email.me', 'password', 'secret', 'totp_callback', 'platform');

// You can also disable the SSL verify peer, when you're having issues with your environment. Simply pass true as the latest parameter
// $api = new \JKetelaar\fut\bot\API('your@email.me', 'password', 'secret', 'totp_callback', 'platform', true); 
```

**Comment by Albvadi** [comment]
Works as expected.

As a detail, to update the package with Composer, I had to change manually in composer.json the versión in the required section, from `^0.0.4` to `0.*`

Anyways, works great. 
Thanks!!

**Comment by JKetelaar** [comment]
Yep, realised too late that `0.0.4.1` wouldn't work, as it's meant for development releases. 
I'll release a `0.1.*` later on, to avoid such issues!
