### ISSUE TITLE
[ERROR 295712] Incorrect verification code

### ISSUE THREAD

**Issue by Albvadi** [JKetelaar/PHP-FUT-API#27]
Hi, trying to use the APi, I get the following error:
`Fatal error: Uncaught JKetelaar\fut\api\errors\login\MainLogin: Unable to login with unknown response With the following message: Incorrect verification code With error code: 295712 in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php:377 Stack trace: #0 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php(94): JKetelaar\fut\api\user\Login->postTwoFactorForm('https://signin....') #1 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\API.php(114): JKetelaar\fut\api\user\Login->login() #2 C:\xampp_7\htdocs\fut17\index.php(8): JKetelaar\fut\api\API->login() #3 {main} thrown in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php on line 377`

Using the example in the readme, I´m changing:
- your@email.me --> My correct email
- password --> My account password
- secret --> My answer to the security question
- totp_callback --> Don´t change
- platform --> 'ps4'
- SECRET (in totp_callback function) --> My answer to the security question

It´s this correct??
Each time I try the login and get the error, I receive an email with the security code

Thanks!!

**Comment by JKetelaar** [comment]
To be sure, you have set email as your two step authentication?

**Comment by Albvadi** [comment]
Well, I´ve checked my setup in the EA page.
I have enable the Login Verification and set email. 

If I disable this, I get the following error:
`Fatal error: Uncaught JKetelaar\fut\api\errors\login\MainLogin: Unable to login with unknown response With the following message: Page not matching login form page (Account Update) With error code: 281658 in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php:348 Stack trace: #0 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php(92): JKetelaar\fut\api\user\Login->postLoginForm('https://signin....') #1 C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\API.php(114): JKetelaar\fut\api\user\Login->login() #2 C:\xampp_7\htdocs\fut17\index.php(8): JKetelaar\fut\api\API->login() #3 {main} thrown in C:\xampp_7\htdocs\fut17\vendor\jketelaar\php-fut-api\src\JKetelaar\fut\api\user\Login.php on line 348`

**Comment by JKetelaar** [comment]
Thanks, I'll test this with email, I will get back asap

**Comment by JKetelaar** [comment]
Just released V0.0.5, which seems to work for me using Email authentication. 
Can you test this for me with your account?

**Comment by Albvadi** [comment]
Nope, still with same error...
I run index.php with this:
```php
$api = new \JKetelaar\fut\api\API('my-email', 'my-password', 'my-secret-answer-question', 'totp_callback', 'ps4', true);
```
And the login fails. I receive a email with my code and update in index.php:
```php
function totp_callback() {
    $totp = new \OTPHP\TOTP('FIFA', 'my-code-received');
    return $totp->now();
}
```
run index.php again and nothing, same original error...

**Comment by JKetelaar** [comment]
Change your `totp_callback` function to:

```
function totp_callback() {
    return 'my-code-received;
}
```

As it's an email code, no TOTP is required :)

**Comment by Albvadi** [comment]
Great!
Works perfectly 😃 

Thanks!!
