### ISSUE TITLE
How to access players sent to the tradepile?

### ISSUE THREAD

**Issue by suckedjs** [JKetelaar/PHP-FUT-API#41]
I am trying to get the PlayerIDs (not the MaskedID or ResourceId as EA call it) of all the players that I sent to the tradepile. I managed to get the ResourceId of each card but how do I access the getBaseId() from the Player Class from here?

This is my current code: 
```
if($api->login() === true) {
    echo('We\'re logged in!' . "\n");

    $handler = $api->getHandler();
    foreach($handler->getTradepile() as $trade => $value) {
    	if ($value->getItemData()->getItemType() == "player") {
    		
			echo $value->getItemData()->getResourceId()."<br />";

    	}
    }   
}

**Comment by JKetelaar** [comment]
You could do:
```
$id = $value->getItemData()->getAssetId();
```

AssetId sort of equals BaseId, look over [here](https://github.com/JKetelaar/PHP-FUT-API/blob/6853c0d27c45a52677f65ae928ffe004fe5a6863/src/JKetelaar/fut/api/database/models/Player.php#L73).

**Comment by suckedjs** [comment]
$value->getItemData()->getResourceId() did the trick. It was under my nose for the entire time
