### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by ToniKuipers** [JKetelaar/PHP-FUT-API#42]
I got an error with the example login php. The error is on line 188 of API.php. What does the line mean?

`  public function login($path = DATA_DIR . '/cookies.txt') {`

I'am also not understanding this line of the bootstrap.php

`define('DATA_DIR', (($dir = drush_server_home()) === null ? __DIR__ : $dir) . '/.fut-bot/data/');`

Please help!

**Comment by JKetelaar** [comment]
It's the login method with a cookies file to store the cookies in 🍪.

The line in `bootstrap.php` defines what `DATA_DIR` should be.
