### ISSUE TITLE
Search for players

### ISSUE THREAD

**Issue by ToniKuipers** [JKetelaar/PHP-FUT-API#46]
I'am doing something wrong right?

```
if($api->login() === true) {
    $searcher = $api->getHandler()->getSearcher();
    $players = $searcher->searchFor(\JKetelaar\fut\api\market\items\ItemType::PLAYER(), [], 0, 50);
    echo $players;
}
```

No error's but only echo the word array.

**Comment by Albvadi** [comment]
Change `echo $players;` for `print_r($players);`

And with format:
```php
echo "<pre>";
print_r($players);
echo "</pre>";

```

**Comment by ToniKuipers** [comment]
Thanks, great job!
Do you know how to echo a part of the array?

Something like:

`echo $players[0]['id'];`

And how to buy a player when it found something?

**Comment by JKetelaar** [comment]
```
echo $players[ 0 ]->getId():
```

**Comment by ToniKuipers** [comment]
Thanks!

What about the buy a player part? Is that possible?

**Comment by JKetelaar** [comment]
Are you referring to the buying part? An example of that will appear soon, stay tuned!

**Comment by ToniKuipers** [comment]
That would be amazing!!!

**Comment by ToniKuipers** [comment]
Any news on the buying part?
