### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by ToniKuipers** [JKetelaar/PHP-FUT-API#47]
It it possible to store the session? So I don't have to log in every time i refresh the page.

**Comment by JKetelaar** [comment]
Yes, store it in a cookies file.

```
define('DATA_DIR', __DIR__ . '/data/');
```

**Comment by ToniKuipers** [comment]
Thanks!

But this should be working, i'am already logged in on another page.

```
<?php
require_once('vendor/autoload.php');

define('DATA_DIR', __DIR__ . '/data/');

if($api->login() === true) {
    echo('Logged in');
}
```

I get this error.
`
Fatal error: Uncaught Error: Call to a member function login() on null in /home4/tonikuipers/public_html/mydomain.com/test.php:6 Stack trace: #0 {main} thrown in /home4/tonikuipers/public_html/mydomain.com/test.php on line 6`

**Comment by JKetelaar** [comment]
$api is nu, make sure to create that variable first.

**Comment by ToniKuipers** [comment]
Thats's right, but when I do that with this code i have to pass my login details and TokenFunction.

```
$api = new \JKetelaar\fut\api\API(
    $creds[ 'username' ], $creds[ 'password' ], $creds[ 'secret' ], $creds[ 'key' ], $creds[ 'platform' ]
);
```
How to avoid that?

**Comment by JKetelaar** [comment]
See issue #49
