### ISSUE TITLE
totp_callback Function

### ISSUE THREAD

**Issue by suckedjs** [JKetelaar/PHP-FUT-API#52]
What exactly is this SECRET. I believe this is not the secret answer of my FUT account. Should I use one of the backup codes? 

function totp_callback() {
    $totp = new \OTPHP\TOTP('FIFA', 'SECRET');

    return $totp->now();
}

**Comment by JKetelaar** [comment]
This is meant to be the secret given by the two-factor authentication of EA.

The following code:
```
function totp_callback() {
    $totp = new \OTPHP\TOTP('FIFA', 'SECRET');

    return $totp->now();
}
```

Should only have `SECRET` adjusted to your matching secret two-factor authentication code.
ie.:
```
function totp_callback() {
    $totp = new \OTPHP\TOTP('FIFA', '2O1FUH2XFEXK1528');

    return $totp->now();
}
```

**Comment by suckedjs** [comment]
Thanks! But where do I find this secret? inside the Google Authentificator  or ?

**Comment by JKetelaar** [comment]
When setting up the system, it lets you scan a QR-Code, but also allows you to grab the code if you can't  scan the code. Use that option and save the code, which is the secret.

**Comment by suckedjs** [comment]
Cheers! This should be included in the documentation.

**Comment by JKetelaar** [comment]
I'll still need to find time to create some sort of documentation 😿
