### ISSUE TITLE
Fatal Error when calling $handler->getTradepile()

### ISSUE THREAD

**Issue by suckedjs** [JKetelaar/PHP-FUT-API#53]
It started 3 hours ago. 
  $handler = $api->getHandler();
    foreach($handler->getTradepile() as $trade) {
        // Interact with $trade here
    }
will result in 
Fatal error: Uncaught exception 'BadMethodCallException' with message 'No static method or enum constant '_DEFAULT' in class JKetelaar\fut\api\market\items\ItemType' in C:\xampp\htdocs\ea\vendor\myclabs\php-enum\src\Enum.php:184 Stack trace: #0 C:\xampp\htdocs\ea\src\JKetelaar\fut\api\ImprovedEnum.php(33): MyCLabs\Enum\Enum::__callStatic('_DEFAULT', Array) #1 C:\xampp\htdocs\ea\src\JKetelaar\fut\api\ImprovedEnum.php(33): JKetelaar\fut\api\ImprovedEnum::_DEFAULT() #2 C:\xampp\htdocs\ea\src\JKetelaar\fut\api\market\trading\ItemData.php(141): JKetelaar\fut\api\ImprovedEnum::findByKey('gkCoach', true) #3 C:\xampp\htdocs\ea\src\JKetelaar\fut\api\market\trading\Trade.php(125): JKetelaar\fut\api\market\trading\ItemData::toObject(Array) #4 C:\xampp\htdocs\ea\src\JKetelaar\fut\api\market\Handler.php(144): JKetelaar\fut\api\market\trading\Trade::toObject(Array) #5 C:\xampp\htdocs\ea\sell.php(16): JKetelaar\fut\api\market\Handler->getTradepile() #6 {main} thrown in C:\xampp\htdocs\ea\vendor\myclabs\php-enum\src\Enum.php on line 184

Any clues?

**Comment by suckedjs** [comment]
works fine this morning. It has to be something to do with the ea servers?

**Comment by JKetelaar** [comment]
Maybe there was some sort of downtime?

Seems like they had some issues yesterday: http://downdetector.com/status/ea
