### ISSUE TITLE
Hi , how to contact you? I want to invite you develop a project about fut api.

### ISSUE THREAD

**Issue by h1100e** [JKetelaar/PHP-FUT-API#56]
Hi , how to contact you? I want to invite you develop a project about fut api.

**Comment by JKetelaar** [comment]
Hi there!
You can reach out to me on Discord; JKetelaar#8145

**Comment by h1100e** [comment]
Can give me your telegram,twitter,skype or other private chat?

**Comment by JKetelaar** [comment]
Telegram username is @JKetelaar

**Comment by h1100e** [comment]
Why not reply me in Telegram? Can you see the message plz?
